language: python
python:
    3.7
services:
- docker
install:
  - pip install -U pip
  - pip install -U tox
script:
  - cd server
  - pip install -r requirements.txt 
  - pip install -r test-requirements.txt 
  - tox
