language: python
python:
    3.7
services:
- docker
install:
  - pip3 install -U pip
  - pip3 install -U tox
script:
  - cd server
  - pip3 install pythonql3==0.9.61
  - pip3 install -r requirements.txt 
  - pip3 install -r test-requirements.txt 
  - tox
