language: python
python:
    3.7
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.23.2
  global:
services:
- docker
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
- sudo apt-get install nodejs
- npm install --global release-it
install:
    - cd server
    - pip install  pythonql3==0.9.61
    - pip install -r requirements.txt
script:
    - tox
deploy:
  provider: script
  script: bash .deploy
  on:
    tags: true
    all_branches: true
  skip_cleanup: true

