language: python
python:
    3.7
services:
- docker
install:
  - pip install -U pip
  - pip install coverage
  - pip install codecov
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install --upgrade setuptools wheel
script:
  - cd server
  - pytest
after_success:
- codecov

