language: python
python:
    3.7
services:
- docker
install:
  - pip3 install -U pip
  - pip3 install -U tox
  - pip install --upgrade setuptools wheel
script:
  - cd server
  - pip3 install -r requirements.txt 
  - pip3 install -r test-requirements.txt 
  - tox
