language: node_js
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.23.2
  global:
  - secure: qA5b0/qoDh78rEXPk4krOlpQQTRBs5ewo6d+R5ilV6hw4QorBKmI7FTiz7aM8hzup/kOlxvGc5M52uUi3MUwQjdbORbMIXxViUH17f5rPBiI/2mp8XbQEGwlcP5dFTR8I0Ia1TlXRSeQ19VSqkLWUUlrpkcqpT8OuYe7g1/b8WYcHUZVpUiZbCxvKjWsrxXQ9e6y7NfcmokQ27UbyHtNNPyWR2NShsaqO1gkL+GhTb8DGPxnn9qyC0FszZtykzakz2EyRtDOnt4zygYlsuYXJTZ3C7lY90qnYz2WEWqEIrI4W1S2/ascwJty3ur9Ap6fhAvOEJfYZKxSvVaVAMzLKj6SXZDC0B2iva95E2r8ECT2qqN2vtIBRvqf8MiSboY935k9Fq/z79RDSAuP/qBIq2hTatmGpuT5bradIYzZ0+rjrWLspnr/PsJrieE087ORRcJf+1ROdr3f/jTfIhUn0z/rknd0MSrpIrxAs8LdQ1wCDzEWCr6maJmDaNdQY1zE4REbkfnOqv88h65VZOCYEeOh8P/LF9k7893zl8+Z8CwYKB4KJ6LMwBRJ8/c8BX1jaI0jED3UWNG/AiMNMkHZaoxm5OiEdlFzJqP9yCmfNwfpPASz7FB2vvW7oc776JW5vTbrfhrWFq3fZp5/yNR9EhgiRpWEPmAKwGO5BwGuRCU=
  - secure: hjdP/exjse9GC3ubr9xUgvkA5cfF2aKXRvpZ1XWdlsShXo+8EF8U4l8T4yihKDLrijM0vwguDPNqCTWMjRqtNiwMbPA8zdbpXR+cMIloepX0Ms/Fix1jvgqGcLl3Dmy7A1/JG9GC9zbbb5C4HoZKghQurmXiKOwO+RmNNNGi9Sg9NNU5Firk5ABfscl3KGoBxMLYm6myGa52G7RrrA6cc8n42kr2YzPIjVqjXyBFvOqmhMqccLmoXEWRkCOSA3LDoD6xeecx2K+ir6+VmDWDo/9FvB+mv5YQlSQ6HafJJxTR35zFXU+FB9CEegAEL49NyPUExt/e30A1qDWzChqp5BduEAM7AY7CZ8lHn+XiS39itIWAaj6pIXcrbUaAGVUwR1o3YohE8CSYWzkqFFCK6xF3UHTjBFKDv6frzaf6tBI9I9eJeYQevzIDq3fjkWuwRMSWV2KT7AzGf/M95Tpuv68qSgI+okxh5J9XIUXkm9tx/jAedON+snn1DkD56xfZCerIeMxxNutELvrJY39DmI/tgfzU7XalWoyrEjJNdMUUKyLh53ax3rXdRj/vhzOpQg6kiHqB3gF74QWCKTV33Lluptdv+Zyishu12ttxHSCExXtUAiDYUab0JDnr5lsOtnlMl8gjt5KvBvTHPdSgRoaZAqXTFVsCwVfZQKiBU1E=
services:
- docker
before_install:
- npm install --global release-it
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- cd server
- docker build -t model-catalog-api .
- docker tag model-catalog-api mintproject/model-catalog-api:latest
- docker push mintproject/model-catalog-api:latest
deploy:
  provider: script
  script: bash .deploy
  on:
    tags: true
    all_branches: true
