site_name: Model Catalog Python client
nav:
  - Home: index.md
theme: 
  name: material
  logo: 'logo.png'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
