version: '3'
services:
  dev:
    image: "mintproject/model-catalog-api:${VERSION}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:8080
    volumes:
      - ./openapi_server/openapi/:/usr/src/app/openapi_server/openapi/

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "${SWAGGER_PORT}:8080"
    volumes:
      - "./:/tmp/"
    environment:
      SWAGGER_JSON: "/tmp/openapi.json"
      BASE_URL: "/v1.5.0/ui"
