version: '3'
services:
  api-local:
    image: "mint-project/api-modelcatalog:dev"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
  db-local:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

