version: '3'
services:
  api-dev:
    image: "mint-project/api-modelcatalog:dev"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:8080
  db-dev:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: users
      MYSQL_USER: api
      MYSQL_PASSWORD: example
